Repository hygieia/hygieia-codequality-sonar-collector, pull requests merged in 2020-08, with the labels that each got.

#49 Fix excessive number of Sonar exceptions from 404
  src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
  src/main/java/com/capitalone/dashboard/collector/SonarClient.java
  src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java
Labels: ✅ Approved

#53 Added sonar project error check for 404 possibility
  pom.xml
  src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java
Labels: ✅ Approved

#56 Updated version of snapshot for log checks.
  pom.xml
Labels: 🔍 Ready for Review

#55 update mongodb 3.6.x to support AWS DocumentDB
  pom.xml
Labels: ✅ Approved

#57 Security Vulnerabilities Fix
  pom.xml
Labels: 🔍 Ready for Review

#58 Log changes for updated or new projects and checking errors
  src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java
Labels: ✅ Approved

#59 Upgrade core to 3.8.0 and adapt RestClient change
  pom.xml
  src/main/java/com/capitalone/dashboard/collector/RestOperationsSupplier.java
  src/main/java/com/capitalone/dashboard/collector/SonarClientSelector.java
  src/main/java/com/capitalone/dashboard/collector/SonarSettings.java
  src/test/java/com/capitalone/dashboard/collector/DefaultSonar6ClientTest.java
  src/test/java/com/capitalone/dashboard/collector/DefaultSonar8ClientTest.java
  src/test/java/com/capitalone/dashboard/collector/SonarClientSelectorTest.java
Labels: ✅ Approved, 🔍 Ready for Review

#60 removal of clean for sonar exceptions
  src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java
Labels: ✅ Approved

#62 Update pom snapshot for sonar changes
  pom.xml
Labels: ✅ Approved
