Repository hygieia/hygieia-codequality-sonar-collector, pull requests merged in 2020-10, with the labels that each got.

#68 Sonar projectId null check
  pom.xml
  src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java
Labels: ✅ Approved, 🔍 Ready for Review

#67 README update Sonar
  README.md
Labels: ✅ Approved

#70 sonar refresh data by individual project
  pom.xml
  src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
  src/main/java/com/capitalone/dashboard/collector/DefaultSonarClient.java
  src/main/java/com/capitalone/dashboard/collector/SonarClient.java
  src/main/java/com/capitalone/dashboard/controller/SonarController.java
  src/main/java/com/capitalone/dashboard/repository/SonarProjectRepository.java
  src/main/java/com/capitalone/dashboard/util/SonarCollectorUtil.java
Labels: 🔍 Ready for Review
